temp_folder: /n/fs/visualai-scr/temp_LLP/ellie
data_root: /n/fs/visualai-scr/Data/Kinetics_cvf/frames  # Root directory for video frames
device: cuda  # Will need to be dynamically determined in code
metadata_dir: /n/fs/visualai-scr/temp_LLP/ellie/slowfast_kinetics  # Directory containing curated CSV files
batch_size: 16  # according to paper
learning_rate: 0.01
num_epochs: 196